backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title | slugify}}"
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "publishedAt", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "Excerpt", name: "excerpt", widget: "markdown" }
      - { label: "Tags (comma separated)", name: "tags", widget: "list" }
      - { label: "Author", name: "author", widget: "string" }
  - name: "cats"
    label: "Cats"
    folder: "src/content/cats"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Age", name: "age", widget: "number" }
      - { label: "Gender", name: "gender", widget: "select", options: ["male", "female"] }
      - label: "Personality"
        name: "personality"
        widget: "list"
        hint: "One trait per line"
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Instagram Link", name: "link", widget: "string", required: false }
      - { label: "Published At", name: "publishedAt", widget: "datetime", required: false }
      - { label: "Special Needs", name: "isSpecialNeeds", widget: "boolean", required: false }
      - { label: "Slug", name: "slug", widget: "string", required: false }